### ISSUE TITLE
Typo mistake in consts-headers.js

### ISSUE THREAD

**Issue by hubbergit** [aetheric/http-constants#2]
Hi,

note that there is a typo mistake in consts-headers.js, the export should be spelled `response` and not `reponse`.

Would be great, if you could fix this.

Thanks in advance.

**Comment by Tzrlk** [comment]
FFS, my life is a joke. Will take care of it.

**Comment by Tzrlk** [comment]
Should be available in npm version 1.1.3-2-g513b3ea

**Comment by hubbergit** [comment]
Works for me!

Thanks!

However please consider to change version number according to semver spec in future version, because renaming was a breaking change here.

**Comment by Tzrlk** [comment]
Legit, but to be fair, all the recent shenanigans with this library have
been (un-)breaking changes.
I'll trigger a proper release now.
