### ISSUE TITLE
Request Origin -> ORIGIN

### ISSUE THREAD

**Issue by andrewvsk** [aetheric/http-constants#3]
Oigin should be in UPPER_CASE:
https://github.com/aetheric/http-constants/blob/513b3ea8831be74d134e755d31e33f0a52393160/src/main/consts-headers-request.js#L198

**Comment by Tzrlk** [comment]
Huh. Good catch. I'll get that patched soon.

**Comment by Tzrlk** [comment]
The fix should be available in 1.1.5.
