### ISSUE TITLE
Can you please add `export const PATCH = 'PATCH';` in consts-methods.js

### ISSUE THREAD

**Issue by atindersingh67** [aetheric/http-constants#5]

**Comment by Tzrlk** [comment]
Sure thing.

**Comment by Tzrlk** [comment]
The change is in, and I'll run a release tomorrow when I have all my kit together.  
I want to get #4 fixed as well, just so I can streamline releases in future.

**Comment by Tzrlk** [comment]
Right, this should now be available in 2.1.0. Let me know if there are any problems.

**Comment by atindersingh67** [comment]
Got the update, Thanks for the support.

**Comment by Tzrlk** [comment]
No problem, happy to help.
